### GET
GET http://localhost:8080/users

### GET with invalid ID
GET http://localhost:8080/users/1

### POST new User
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "John Doe",
    "password": "5d3307f4-50d2-4420-9ea0-96544d1a7bdb",
    "email": "john.doe@newtonpaiva.br",
    "mobile": "+55.31.991234567"
}

### PUT update user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
    "name": "John Doe Jr",
    "password": "5d3307f4-50d2-4420-9ea0-96544d1a7bdb",
    "email": "john.doe.jr@newtonpaiva.br",
    "mobile": "+55.31.991233210"
}

### DELETE
DELETE http://localhost:8080/users/1