/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: waldir.junior@newtonpaiva.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Pet;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PetApi
 */
@Ignore
public class PetApiTest {

    private final PetApi api = new PetApi();

    
    /**
     * Cria un novo Pet.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void criarPetTest() throws ApiException {
        Pet body = null;
        Pet response = api.criarPet(body);

        // TODO: test validations
    }
    
    /**
     * Deleta um Pet da loja a partir do ID.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePetByIdTest() throws ApiException {
        String id = null;
        api.deletePetById(id);

        // TODO: test validations
    }
    
    /**
     * Lista todos os Pets da loja.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPetsTest() throws ApiException {
        List<Pet> response = api.getAllPets();

        // TODO: test validations
    }
    
    /**
     * Retorna um Pet da loja a partir do ID.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPetByIdTest() throws ApiException {
        String id = null;
        Pet response = api.getPetById(id);

        // TODO: test validations
    }
    
    /**
     * Atualiza um Pet da loja a partir do ID.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePetByIdTest() throws ApiException {
        String id = null;
        Pet body = null;
        Pet response = api.updatePetById(id, body);

        // TODO: test validations
    }
    
}
