
GET http://localhost:3000/v1/posts/

###
GET http://localhost:3000/v1/posts/5fcc9da324421c4d8225a2dd

###
GET http://localhost:3000/v1/posts/search?userId=b27b6a48-9ef8-4da2-8b99-10141cc97c39

###
POST http://localhost:3000/v1/posts
Content-Type: application/json

{
    "userId": "b27b6a48-9ef8-4da2-8b99-10141cc97c39",
    "conteudo": "The book is on the table",
    "foto": "http://foto.com/foto.jpg"
}

###
PATCH http://localhost:3000/v1/posts/5fcc9da324421c4d8225a2dd
Content-Type: application/json

{
    "conteudo": "The book is on the table - 2",
    "foto": "http://foto.com/foto2.jpg"
}

###
PUT http://localhost:3000/v1/posts/5fcc9da324421c4d8225a2dd/publicar
Content-Type: application/json

###
DELETE http://localhost:3000/v1/posts/5fcc9da324421c4d8225a2dd

